"""empty message

Revision ID: 15af868ff38f
Revises: 95c8037dd561
Create Date: 2025-11-03 00:46:52.070157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af868ff38f'
down_revision = '95c8037dd561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=180), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
